stages:
  - build
  - deploy

# build-production:
#   stage: build-books
#   script:
#     - DEBUG=gs BOOK_FILE_NAME=mcp2015x npm run build-site
#     - echo "Will trigger mcpx-board-manual-site build...."
#   artifacts:
#     paths:
#       - site
#   only:
#     - master

build-testing:
  image: node:6.10.2
  stage: build
  script:
    - apt-get update
    - apt-get install calibre -y
    - npm install gitbook-cli -g
    - gitbook fetch latest
    - npm i
    - DEBUG=gs BOOK_PRERELEASES=true BOOK_FILE_NAME=/mcp2015x/ BOOK_BASE_URL=manuals/mcp2015x PDF_BASE_URL=/manuals/mcp2015x/ npm run build-site
  artifacts:
    paths:
      - site
  only:
    - develop

deploy-testing:
  stage: deploy
  script:
    - apt-get update
    - apt-get install curl -y
    - curl -X POST -F token=$TRIGGER_TOKEN -F ref=develop https://gitlab.com/api/v4/projects/3354326/trigger/pipeline
  only:
    - develop
