image: node:6.10.2

stages:
  - build-books

before_script:
  - apt-get update
  - apt-get install calibre -y
  - npm install gitbook-cli -g
  - gitbook fetch latest
  - npm i

build-production:
  stage: build-books
  script:
    - DEBUG=gs BOOK_FILE_NAME=mcp2015x npm run build-site
    - echo "Will trigger mcpx-board-manual-site build...."
  artifacts:
    paths:
      - site
  only:
    - master

build-testing:
  stage: build-books
  script:
    - DEBUG=gs BOOK_FILE_NAME=mcp2015x npm run build-site
    - echo "Will trigger mcpx-board-manual-site build...."
  artifacts:
    paths:
      - site
  only:
    - develop
