image: node:6.10.0

stages:
  - build-books
cache:
  paths:
    - node_modules/

before_script:
  - npm install gitbook-cli -g
  - gitbook fetch latest
  - npm i
  - apt-get update
  - apt-get install calibre -y

build-books:
  stage: build-books
  script:
    - DEBUG=gs BOOK_FILE_NAME=mcp2015x npm run build-site
  artifacts:
    paths:
      - site
  only:
    - master
    - develop
    - tags
