stages:
  - build
  - deploy

# build-production:
#   stage: build-books
#   script:
#     - DEBUG=gs BOOK_FILE_NAME=mcp2015x npm run build-site
#     - echo "Will trigger mcpx-board-manual-site build...."
#   artifacts:
#     paths:
#       - site
#   only:
#     - master

# build-testing-local:
#   image: node:6.10.2
#   stage: build
#   script:
#     - apt-get update
#     - apt-get install calibre -y
#     - npm install gitbook-cli@2.3.0 -g
#     - gitbook fetch latest
#     - npm i
#     - DEBUG=gs BOOK_PRERELEASES=true BOOK_FILE_NAME=$BOOK_FILE_NAME BOOK_BASE_URL=/ PDF_BASE_URL=/ npm run build-site
#   artifacts:
#     paths:
#       - site
#   except:
#     - master
#     - develop

build testing:
  image: node:6.10.2
  stage: build
  script:
    - apt-get update
    - apt-get install calibre jpegoptim optipng -y
    - npm install gitbook-cli@2.3.0 -g
    - gitbook fetch latest
    - npm i
    - DEBUG=gs BOOK_PRERELEASES=true BOOK_FILE_NAME=$BOOK_FILE_NAME npm run build
  artifacts:
    paths:
      - site
  only:
    - /^v\d+\.\d+\.\d+-(alpha|beta|rc)\.\d+$/
  except:
    - branches

deploy to testing:
  image: python:2.7.14-jessie
  stage: deploy
  script:
    - pip install s3cmd
    - s3cmd sync --access_key=$S3_ACCESS_KEY --secret_key=$S3_SECRET_KEY --host=$S3_HOST --host-bucket=$S3_HOST_BUCKET --acl-private --delete-removed --dry-run ./site/public/ s3://$TESTING_BUCKET_NAME/$PUBLIC_PATH
    - s3cmd sync --access_key=$S3_ACCESS_KEY --secret_key=$S3_SECRET_KEY --host=$S3_HOST --host-bucket=$S3_HOST_BUCKET --acl-private --delete-removed --dry-run ./site/pdf s3://$TESTING_BUCKET_NAME/$DOWNLOAD_PATH
  only:
    - /^v\d+\.\d+\.\d+-(alpha|beta|rc)\.\d+$/
  except:
    - branches
  environment:
    name: testing

# deploy-testing:
#   stage: deploy
#   script:
#     - apt-get update
#     - apt-get install curl -y
#     - curl -X POST -F token=$TRIGGER_TOKEN -F ref=develop https://gitlab.com/api/v4/projects/3354326/trigger/pipeline
#   only:
#     - develop
#   environment:
#     name: testing
