language: node_js
node_js:
- '8.9'
before_script:
- sudo apt-get install calibre xvfb jpegoptim optipng -y
- npm install -g gitbook-cli
- gitbook fetch 3.2.3
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run build
branches:
  only:
  - master
  - develop
deploy:
  provider: s3
  skip_cleanup: true
  upload-dir: testing
  local_dir: artifacts
    tags: "/^v\\d+\\.\\d+\\.\\d+-(alpha|beta|rc)\\.\\d+$/"
env:
  global:
  - secure: 7EJDJZt+8VjNUiOT+QGQVMW7DGucebtJO1cDDBN0NIk5/yPbN5T65klH0KQ8J7VlcU17sB/PPLu4Jnm74MciTyoVhTlzRmHcpFY6N6HvQDm0MUi9TtoGgJZYZqgfzBtHjWgG8MU1SZtl+Yi7+X4Cr9dQRXAmmUUpQ4+qOA8PcZwSRWPOXzrYINehDH/3n9Z6ZMTWauCUWVPYbfDcDqbqY5t4826w++wiU7LMYJA/gx63UeEkh8kJpDf7dqBfGTMHmfhi/30ID1QQfiPWGe6TWAMxNZYII6+3Gwwd51aczNzs+g/9pGeSRJ0xFEdaYWewrWTzqenJ6qI9tYwUD+f6ROb8kMB2mfNvGpTf8e5ufR9eDLgIC5m0xhiN6aBZrx7/hBLj23BG2sXQyX/v+iEHI2/p8F7OhtDl6NP9NBG8OPzaxNPjy/YzXzVU61c8j8r52l9+JleftkBKZi8G3vh4ZRu7eHr7H6FWNbF8xY8q4ypLT1U/xcmSYOawQm/AB7x7DhgaKnc4Si//jZP9XfDJhoR9SMyMh8yPdUVcITz7SHBDGJn63RpteaH+OdeAqp629I7Kgmb/6WkZIDjxGdvD85sTmGiNtGbvzINTRi5BlFqJLeqa0CH9mxHg7D8cbswnAjNyCTOv3vi+K29bzFZVG12BqIMv2BGWAfOIOatM2Z8=
  - secure: K0oE7dUkEtulcVzZLaMIkzFciP1Es0hO5w3/1Pe6XfRYzqAsSKI4Te7LxKx2l/rUqi3KGrMwwMa/+ilOWrqsL3+xyX5acj5D9Cv0aUGrPmZbnPvsPRijwSBwaCEvzMK8lMlfWdVBLKULYoeY4XBCJQjuGws6OTaZo4K+rEX0VMhyO7ZqQh/KZWNYgdnsqx3sBvIozaId8r9yH0LqESWPRt3/px+inwx0NWjKkGKizpKKAQvkyN8nxL/4wXOXyQlCOeejQRbVAc8GeQzXLs8dPlTJS50KzqJMAH6wATphm1DCfS2YGLN9mcoSO47qSAv+GsjIcBEE6m9zPjPxEkB5eu7Zplm14cuE18HtUsY1AU9F1uzHbnur8tM96XTY0Me0PYFZxaL7rOIW1LWLJFcfhpBRnqkUU291YZc47zWUt5G7/CgWh1KxOUjRMokm4Sy3zDFilneFV5+3aempiLdBLsUcePIY9Zj2zlyBBrxfDhZqg8gfsxexkwNJTEEW+I0hcJ5siFivkiLtdplQKIjPYPxt6cGjex1GxNfP39BR4Chyrjj0sN/UB5rfLWB9SO/xvmB/1zcQ2+E8AybmnzNJOnKQA0wAN53o04+KWHcOGfdV+rTKCjBp6faEH39DdgjgTciP0wCwPQZ3s/Lg2ACbXXCkFGE9qHsMZfxA9apaG80=
  - secure: t0XY8auMIj6JG0Cg81aYY0rL37Z0DZCknEpe19R51HWsUAOuy8IHyQv72y33tJyATP7vtHOKB8EpEvOTdfwm7Gmp5zfo4YppRfKAxl19ngI+nyE46zRdCFgFwyHwOVyPdJA70UceW/2rUngdh3otXwADfsf7d0IquQ62EfIjuO661zIiopUI5maB/betMh75h0jpo10apRklGvR+CRjceiP14hnDTX0ZFxpVeSXID/6bLPV2nCA8eUeZv1zBdg/UXxBv+CxBRHlWDpl4kFHPRTEpGCBImOTHY13fW8TOzbLR1RalQZYLqbseOM9AtjUW++l3b+Gr2tYYvmMxM2jnA6rEAn1X5hpXsL29u/Lc9P5T1lQ4msXU6tT9RKO7ZJTtzIzL1DyPmQ87PRfv+k1A86F19iWhy8QDfEMBIp8I0JA+6ymA1LgIsmpmNITSUgigo4RY4KtqJx+ywhPY4/OpGH+/i46nSr8AhtC6A95LGXn6jDJLJpQmukUaDT8nz7OF3Woc36HThLKx5GwAmOgsPFbvL306u9gaCmyPE/TFA4KeBQIz8zZfWRjSLCF1dQXgl15NdC1IlYSN8u0rcXCJTqiGPrTtObgXjt7NAPHtAiF2CuFRu1W2csp6z3+P/p2+hXVmzHO2X+HfAk3zbUl+OylAeC5XoszRcD8kAf2GsDA=
