language: node_js
node_js:
- '8.9'
before_script:
- sudo apt-get install calibre xvfb jpegoptim optipng -y
- npm install -g gitbook-cli
- gitbook fetch 3.2.3
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run build
deploy:
  provider: s3
  skip_cleanup: true
  upload-dir: testing
  local_dir: artifacts
  acl: private
  on:
    tags: "/^v\\d+\\.\\d+\\.\\d+-(alpha|beta|rc)\\.\\d+$/"
env:
  global:
  - secure: R9HE4O4aMLMrC9e72lLLNjuq8lwf7uwPUZRUfXZyPBbyrVm441IlJ7eUjV6wBVaArF9hMISAo8BISkYYVjIvwkXEW7p/MeDR4NE76Y3V2D5ghVIw0xo5mW5D+p1J9VenSn2ykvC2t30N5nnCONaLZRuwknHe7BQxGIAUcZVLH02xV0nFJTglIP34rMr4zbds/HTXVcOBEUQSZGZG1kfn/J7FZm9L1KQrE4et62WUfCiYak3iGEGC015nMK8q4WDkn1ynvFyh1AqAA1Ko/cLJ4YzhHRdnIOLpHEhwGJJcobKCdvV9FNHp7zJZtEI8gxhfWvqCnbadR/yvQtLKrRESsDOt5z+PDPPFFCW5HNnLOUjaNUGlk7ulANE1xB1mpk0XcCIpaN+r09d+AHsgf1mQF46+2ZeBhX+9gl0veZD937Uk4F8q0Su6PbUDHErnw5+DZ6aZfVg1CgJtIQwCxWvuyxAf+bfWt/S3SHRfH9DrfxV6aWlYKc++MNZueYQ4VSa1GKJnoPQT86UxkDOIpQ9u0x3d7AEr/yyGuFtRFnKQGtFmhTzn8S4p/7DZoYPmxpVP1iMNCmwJFAodk8YtjEqlvGYEKxio1YP5rv7YLrl3U2/vYrzrpxvG+Qo0ZEWeWM8vNebLWC6Xk6sC8MeK6h6HIqbW8WvM1yL3YkDLzg+MTR0=
  - secure: 7EJDJZt+8VjNUiOT+QGQVMW7DGucebtJO1cDDBN0NIk5/yPbN5T65klH0KQ8J7VlcU17sB/PPLu4Jnm74MciTyoVhTlzRmHcpFY6N6HvQDm0MUi9TtoGgJZYZqgfzBtHjWgG8MU1SZtl+Yi7+X4Cr9dQRXAmmUUpQ4+qOA8PcZwSRWPOXzrYINehDH/3n9Z6ZMTWauCUWVPYbfDcDqbqY5t4826w++wiU7LMYJA/gx63UeEkh8kJpDf7dqBfGTMHmfhi/30ID1QQfiPWGe6TWAMxNZYII6+3Gwwd51aczNzs+g/9pGeSRJ0xFEdaYWewrWTzqenJ6qI9tYwUD+f6ROb8kMB2mfNvGpTf8e5ufR9eDLgIC5m0xhiN6aBZrx7/hBLj23BG2sXQyX/v+iEHI2/p8F7OhtDl6NP9NBG8OPzaxNPjy/YzXzVU61c8j8r52l9+JleftkBKZi8G3vh4ZRu7eHr7H6FWNbF8xY8q4ypLT1U/xcmSYOawQm/AB7x7DhgaKnc4Si//jZP9XfDJhoR9SMyMh8yPdUVcITz7SHBDGJn63RpteaH+OdeAqp629I7Kgmb/6WkZIDjxGdvD85sTmGiNtGbvzINTRi5BlFqJLeqa0CH9mxHg7D8cbswnAjNyCTOv3vi+K29bzFZVG12BqIMv2BGWAfOIOatM2Z8=
  - secure: K0oE7dUkEtulcVzZLaMIkzFciP1Es0hO5w3/1Pe6XfRYzqAsSKI4Te7LxKx2l/rUqi3KGrMwwMa/+ilOWrqsL3+xyX5acj5D9Cv0aUGrPmZbnPvsPRijwSBwaCEvzMK8lMlfWdVBLKULYoeY4XBCJQjuGws6OTaZo4K+rEX0VMhyO7ZqQh/KZWNYgdnsqx3sBvIozaId8r9yH0LqESWPRt3/px+inwx0NWjKkGKizpKKAQvkyN8nxL/4wXOXyQlCOeejQRbVAc8GeQzXLs8dPlTJS50KzqJMAH6wATphm1DCfS2YGLN9mcoSO47qSAv+GsjIcBEE6m9zPjPxEkB5eu7Zplm14cuE18HtUsY1AU9F1uzHbnur8tM96XTY0Me0PYFZxaL7rOIW1LWLJFcfhpBRnqkUU291YZc47zWUt5G7/CgWh1KxOUjRMokm4Sy3zDFilneFV5+3aempiLdBLsUcePIY9Zj2zlyBBrxfDhZqg8gfsxexkwNJTEEW+I0hcJ5siFivkiLtdplQKIjPYPxt6cGjex1GxNfP39BR4Chyrjj0sN/UB5rfLWB9SO/xvmB/1zcQ2+E8AybmnzNJOnKQA0wAN53o04+KWHcOGfdV+rTKCjBp6faEH39DdgjgTciP0wCwPQZ3s/Lg2ACbXXCkFGE9qHsMZfxA9apaG80=
